### ISSUE TITLE
Support for vector or matrix valued parameters

### ISSUE THREAD

**Issue by bgroenks96** [rafaqz/ModelParameters.jl#24]
Just found this package, it looks great! Seems to address a lot of the issues I have been struggling with for the past year w.r.t to parameters and optimization.

I have plans down the road to play around with more complex functions (e.g. neural networks) in my model that may require large vectors or matrices as parameters. How would that fit into the `ModelParameters` framework?

It seems that, at the moment, `Param` allows `val` to be a vector or matrix (though it's not clear that this makes sense since it is supposed to act like a number?), but this gets a bit awkward when collecting the parameter values `collect(model[:val])` since it ends up being of type `Any` if you have a mix of scalar and vector/matrix parameters.

I can imagine that it might be possible to do write a function more clever than `collect` that takes this into account and flattens the matrix/vector parameters. But I suppose this would introduce some difficulties when reconstructing.

Do you have any ideas at the moment as to how this could be handled?

**Comment by bgroenks96** [comment]
I should add that, for relatively small vectors and matrices, it seems the recently added `StaticArray` support would do. But this might not scale well in the more general case.

**Comment by rafaqz** [comment]
Yeah it was written for single parameters. But you should be able to use it like that with minor modifications.

First you dont need to use `collect`, just do `model[:val]` to get a tuple of all the parameter values, which will be type stable. Then use e.g RecusiveArrayTools.jl to combine them. Or maybe use ComponentArrays.jl to build the parameters at the start from a single vector.

Please let me know how it goes or if you have any oroblems, I do want to support this use case.

**Comment by bgroenks96** [comment]
@rafaqz Cool, yeah that's what I was thinking. I am already using `ComponentArrays`, and iirc it allows for scalar components, so that seems like a workable solution. I'll let you know!

**Comment by rafaqz** [comment]
If your Params are mixed vales/vectors you can use Flatten.jl on the `model[:val]` Tuple to just get/modify the vector values only, e.g. with a matching list or component arrays. Then you dont have to write the code explicitly.
