### ISSUE TITLE
Recent changes breaks Flatten process

### ISSUE THREAD

**Issue by ConnectedSystems** [rafaqz/ModelParameters.jl#28]
Not sure if recent changes break ModelParameters.jl or Flatten.jl but in any case specifying the Param type for a field raises an error, whereas it was fine previously:

```julia
Base.@kwdef mutable struct Example
    d::Param = Param(200.0, bounds=(10.0, 550.0))
end

# Model(Example())
# ERROR: ArgumentError: type does not have a definite number of fields

# Appears to work without specifying Param type
Base.@kwdef mutable struct Example2
    d = Param(200.0, bounds=(10.0, 550.0))
end

# Model(Example2())
# Model with parent object of type: 

# Example2

# Parameters:
# ┌───────────┬───────────┬───────┬───────────────┐
# │ component │ fieldname │   val │        bounds │
# ├───────────┼───────────┼───────┼───────────────┤
# │  Example2 │         d │ 200.0 │ (10.0, 550.0) │
# └───────────┴───────────┴───────┴───────────────┘
```

**Comment by bgroenks96** [comment]
This will be fixed shortly by the `Flatten.jl` PR, but FWIW, I wouldn't recommend doing this, especially if your code is performance critical. Using the union type `Param` will make your code type unstable.

You should do:

```julia
Base.@kwdef mutable struct Example{P}
    d::P = Param(200.0, bounds=(10.0, 550.0))
end
```

**Comment by ConnectedSystems** [comment]
Thanks for the advice @bgroenks96

**Comment by rafaqz** [comment]
The Flatten.jl update should be registered in the next half hour, so I'll close this. Thanks for reporting @ConnectedSystems and for the fast fix @bgroenks96!
