### ISSUE TITLE
Extremely long compile times when using ForwardDiff

### ISSUE THREAD

**Issue by bgroenks96** [rafaqz/ModelParameters.jl#31]
I still need to isolate this in a MWE, but I wanted to open the issue for preliminary discussion first.

The time it takes to compile the first `solve` call for my model seems to skyrocket when using `Param`s + `ForwardDiff` types. This doesn't seem to be a problem with `ModelParameters` per-se but rather an issue with inflating type complexity by using autodiff types in all of the model structs containing parameters (I think).

It could be that this is specific to my case, however; maybe it has something to do with the way I wrote my code.

@rafaqz Have you noticed very long compile times with `ForwardDiff`?

**Comment by rafaqz** [comment]
I would just strip the Patams out of the model before doing that.

**Comment by bgroenks96** [comment]
I did, but I used `Flatten.reconstruct` directly due to the type stability issues with `flatten` (and thus `params`) at the moment.

It looks like it might be partially due to the dual tag. By default, it uses the function type, which in my case is a callable struct with a very complex type signature. Changing this to something very short like `Val{gensym(:tag)}` seems to help speed things up.

**Comment by bgroenks96** [comment]
There's still a substantial slow down from what I saw before, though, when the parameters lived only in the passed in parameter array. Maybe this is just unavoidable due to the added type complexity.

**Comment by rafaqz** [comment]
Yeah Ive had problems with Duial numbers being slow. But its unrelated to ModelParameters.jl if youre stripping the params out already...

**Comment by bgroenks96** [comment]
Do you find that it's generally more worth it to do everything out-of-place and then use Zygote?

**Comment by rafaqz** [comment]
I don't know really, zygote compilation takes so long with DyanicGrids.jl rules I haven't pursued it. And only a small fraction of my work is practically differentiable anyway. You probably know much more about this than me.

**Comment by bgroenks96** [comment]
May I ask what methods you use for parameter estimation in the cases where it's not differentiable?

**Comment by rafaqz** [comment]
I do spatial simulations. Often we have scenarios with very rare long distance jumps between cells. And it might follow some weird distribution like distance/population gravity between each cell and all the other cells. It only seems tractable by actually running the simulations.

Writing to random parts of an array isn't differentiable. And for something like this distance/population gravity problem analytically representing the millions of different distributions of destinations seems very hard to do (well beyond me at least).

**Comment by bgroenks96** [comment]
> Writing to random parts of an array isn't differentiable

Do you just mean in-place updates of arrays? That should be differentiable. I do it all the time with `ForwardDiff`.

**Comment by bgroenks96** [comment]
Also, I'm closing this, since I guess it's probably not an issue with `ModelParameters`.

I have some problems with the current implementation of `stripparams` but that can be discussed in a different issue.

**Comment by rafaqz** [comment]
Oh yeah you can use ForwardDiff to write to arrays, but not Zygote.

**Comment by bgroenks96** [comment]
Ah, yes. That's my problem with Zygote as well. I work with a moderate size heat diffusion PDE, and while I have not yet tried solving it out-of-place (i.e. just copy arrays everywhere rather than mutate), I suspect the massive performance loss from GC'ing everything will probably negate the gains of source-to-source autodiff.
