### ISSUE TITLE
fix [compat] for Setfield.jl

### ISSUE THREAD

**Issue by JeffreySarnoff** [rafaqz/ModelParameters.jl#40]
current Project.toml
```
 ..
version = "0.3.3"
 ..
[compat]
 ..
Setfield = "0.6, 0.7"
 ..
```
suggested edit
```
 ..
version = "0.3.4"
 ..
[compat]
 ..
Setfield = "0.6, 0.7,0.8"
 ..
```

(edit, reregister, lather, rinse, ..

**Comment by bgroenks96** [comment]
Does everything still work with Setfield 0.8?

**Comment by JeffreySarnoff** [comment]
It should -- I have not tried it. I am not using Setfield directly.
I use several packages that use Setfield, and when I added one of them -- your [compat] entry forced my local version to be downgraded back to 0.7.x ...

**Comment by rafaqz** [comment]
It normally helps to just make a PR if you want this and have time to make an issue...
