### ISSUE TITLE
Allow customization of component type

### ISSUE THREAD

**Issue by bgroenks96** [rafaqz/ModelParameters.jl#42]
Currently, the `:component` field is set to the type name in all cases.

It would useful in some cases to allow the user to customize the `:component` field for user-defined types; i.e. there should be a method:

```julia
component(::Type{T}) where T = T.name.wrapper
```
for which dispatches may be provided to override the component name assigned to type `T`.

**Comment by rafaqz** [comment]
Sounds good

**Comment by bgroenks96** [comment]
This was resolved by #43
